name: ramble-inc/embarcadero

description: Commit and push files from a GitHub repository to another, and then create a pull request

inputs:
  author-username:
    description: Username for the commit author for the destination repository.
    required: true
  author-email:
    description: Email for the commit author for the destination repository. If unknown, use <>.
    required: true
  mappings:
    description: JSON mapping of src file and dest directory compatible with `cp -r`. e.g. `'[{"src":"/file.txt","dest":"/dest"}]'`
    required: true
  dest-username:
    description: GitHub username/organization for the destination repository.
    required: true
  dest-repo:
    description: Destination repository name.
    required: true
  dest-branch:
    description: '[Optional] Branch name for the destination repository. Default: main.'
    required: false
  create-pr:
    description: '[Optional] Whether to create a pull request after pushing to the destination repository. Default: false.'
    required: false
  dest-pr-base-branch:
    description: '[Optional] Base branch name for a pull request to be created. Default: main.'
    required: false

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.author-username }}
    - ${{ inputs.author-email }}
    - ${{ inputs.mappings }}
    - ${{ inputs.dest-username }}
    - ${{ inputs.dest-repo }}
    - ${{ inputs.dest-branch }}
    - ${{ inputs.create-pr }}
    - ${{ inputs.dest-pr-base-branch }}
    
branding:
  icon: git-commit
  color: green
